// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package flex

type Media struct {
	ID        int    `json:"id"`
	Name      string `json:"name"`
	Path      string `json:"path"`
	Duration  int    `json:"duration"`
	Created   int    `json:"created"`
	Status    string `json:"status"`
	TimePoint int    `json:"time_point"`
	LastSeen  int    `json:"last_seen"`
	Thumbnail string `json:"thumbnail"`
}

type MediaInput struct {
	ID        int    `json:"id"`
	Name      string `json:"name"`
	TimePoint int    `json:"time_point"`
	LastSeen  int    `json:"last_seen"`
}
