// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package flex

type Media struct {
	ID           int    `json:"id"`
	Name         string `json:"name"`
	Duration     int    `json:"duration"`
	LastModified int    `json:"last_modified"`
	Status       string `json:"status"`
}

type Profile struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type ProfileViewingInfo struct {
	MediaID   int `json:"media_id"`
	ProfileID int `json:"profile_id"`
	TimePoint int `json:"time_point"`
	Timestamp int `json:"timestamp"`
}
